### ISSUE TITLE
Remembering hub IP

### ISSUE THREAD

**Issue by Mammad900** [Home-modules/webapp-android#1] opened 2023-05-29 16:42 UTC
Currently the app will ask every time about the hub's IP address and port.

It has to remember the IP and launch the web app directly on subsequent starts.

**Comment by Mammad900** [comment] 2023-05-30 11:34
- [x] Default IP is empty
- [x] Default port is 80
- [ ] Port changes to 443 on checking "is https" and vice versa
- [x] Trim whitespace
- [x] Don't allow "go"ing when IP or port is empty
- [x] Ping the hub and don't allow "go"ing when it is unreachable
- [x] Allow the user go to back to IP selection screen if hub becomes unreachable

**Comment by Mammad900** [comment] 2023-05-30 20:33
> - [x] Port changes to 443 on checking "is https" and vice versa

Doesn't work

**Comment by Mammad900** [comment] 2023-05-31 05:19
> Don't allow "go"ing when IP or port is empty

Works partially

**Comment by mohsenemx** [comment] 2023-06-09 12:05
Remembring works fine, but app fails to display loaded data (from memory)

**Comment by mohsenemx** [comment] 2023-06-26 19:02
This seems to be finally fixed. I'll close this once it's confirmed.

**Closed as completed by mohsenemx** 2023-06-26 19:02 UTC
Labels: enhancement, In Process

**Comment by Mammad900** [comment] 2023-08-01 07:25
>  Port changes to 443 on checking "is https" and vice versa

Still doesn't work.
Also used to go directly to web app on subsequent starts but not anymore
